### ISSUE TITLE
Reserveren error na kiezen tijdslot

### ISSUE THREAD

**Issue by Jimmy-Tran** [Jimmy-Tran/Project-B#42]
Error: Error converting value {null} to type 'System.Int32'. Path '[0].CourseMenu', line 14, position 22.

date : 6 december 2023
timeslot: 16

**Comment by Henno0701** [comment]
Fixed, 16 gives 16.00:00:00 not a valid time slot

**Comment by Henno0701** [comment]
Fixed, 16 gives 16.00:00:00 not a valid time slot
